### ISSUE TITLE
[Request feature] Add support for smart-enter

### ISSUE THREAD

**Issue by boydaihungst** [dawsers/fuse-archive.yazi#1]
Please add support for smart-enter. 
https://yazi-rs.github.io/docs/tips#smart-enter

```
local smart_enter = ya.sync(function()
	local exist, smart_enter = pcall(require, "smart-enter")
	if exist then
		smart_enter.entry()
	else
		ya.manager_emit("enter", {})
	end
end)
```
and replace all `ya.manager_emit("enter", {})` with `smart_enter()`

**Comment by dawsers** [comment]
It wouldn't work like that, probably because of sync/async, so in 678eb1dd5c061722c21c795fd38bf4f57c62e4fb I added an option for the plugin that provides the same functionality, `smart_enter`. You can now initialize the plugin in your `~/.config/yazi/init.lua` like this:

``` lua
require("fuse-archive"):setup({
  smart_enter = true,
})
```

**Comment by boydaihungst** [comment]
Yep. Your code looks much better.
