### ISSUE TITLE
[Docs] missing setup in yazi/init.lua

### ISSUE THREAD

**Issue by boydaihungst** [dawsers/fuse-archive.yazi#2]
Look like you need to update document. 
In  yazi v0.4 need to put this code to `~/.config/yazi/init.lua` to enable this plugin:
```
require("fuse-archive"):setup()
```

**Comment by dawsers** [comment]
You are right, I forgot. Thanks!

d7afb21d59a6f7ce7bee687d9f5ecccb5ee320a0
