### ISSUE TITLE
Bug: can't mount if filename start with "-"

### ISSUE THREAD

**Issue by boydaihungst** [dawsers/fuse-archive.yazi#3]
Fuse-archive can't mount if file name starts with "-". Tried to change to mount path, `ya.quote`, but doesn't seem to work. I use kitty + fish. 
 
![image](https://github.com/user-attachments/assets/e2df064e-83d2-431e-8729-63c3899a0633)
![image](https://github.com/user-attachments/assets/ccd4ec58-b587-43ac-9f9a-454b1377dd8a)

**Comment by dawsers** [comment]
Good catch, thank you! I fixed it in 8fd139d8c44e90e553c6dadf1be082f3b150bd76
