### ISSUE TITLE
Deprecated API after upgrade Yazi to 4.0

### ISSUE THREAD

**Issue by og900aero** [dawsers/fuse-archive.yazi#4]
After Yazi 4.0 version, get info message:

"The first paramtere of entry() has been replaced by the new job instead of the previous args.
Please use job.args instead args to access the arguments in your fuset-archive.yazi plugin.
See #1966 for details: https://github.com/sxyazi/yazi/pull/1966"

**Comment by dawsers** [comment]
Yes, the plugin hasn't been updated to be fully compatible with the changes in Yazi 0.4. I am still in 0.3.3, I will update the plugin as soon as my distribution (Arch Linux) moves to Yazi 0.4

**Comment by dawsers** [comment]
Fixed in 62d30df316f121468a6ba59332dd83231af54488

**Comment by og900aero** [comment]
THe unmount doesnt work for me. I stay mounted folder.

**Comment by dawsers** [comment]
Let's see how you are using the plugin. If I do this, things work as expected:

1. I am in a directory where there is an archive, for example `test.zip`
2. I press `right` while on `test.zip`, and I "enter" `test.zip`. This is just `fuse-archive` auto-mounting the archive at `~/.local/state/yazi/fuse-archive/...`
3. I can navigate/view/copy etc. files from the archive as if I was in another directory.
4. If I want to unmount the archive, I need to navigate **out** of it, and it will get automatically unmounted. So you navigate out of `test.zip`. When you navigate out, `fuse-archive` detects you are out, and takes you back to the directory where `test.zip` is, and unmountsthe archive from `~/.local/state/yazi/fuse-mount/...`., removing the entry for `test.zip`.
5. If you follow these steps, you will see the mounted archive no longer exists in `~/.local/state/yazi/fuse-mount/...`, it has been unmounted.

Of course, if you don't navigate **out** of the archive to its parent, then `fuse-archive` doesn't know you don't want to use the archive any longer, and doesn't unmount it.

Let me know if that is not working for you.

**Comment by og900aero** [comment]
The automount isnt working for me, only the manual:

1. Press m and a key four mounting on scrip.tar.zst
2. Jump into the ~/.local/state/yazi/fuse-archive/scrip.tar.zst.tmp676569ee folder
3. No I see the content of archive: Scripts folder (contains some shell files)
4. When I jump out from Scripts folder I see scrip.tar.zst.tmp676569ee
5. Jump out again and I see fuse-archive, but the mounted point is active

Unmounted manual what I working for me: Jump into the ~/.local/state/yazi/fuse-archive/scrip.tar.zst.tmp676569ee folder, and press m and u key (plugin fuse-archive --args=unmount), and now jump back to the scrip.tar.zst, and mounted folder is gone.

**Comment by dawsers** [comment]
If you have to mount the archive manually, you are probably not using `fuse-archive`, you are probably using some yazi feature, and that is why it is not unmounting later on.

If you want to use the plugin as described in the README, you need to configure some key bindings so things happen automatically:

[Usage](https://github.com/dawsers/fuse-archive.yazi#usage)

Have you done this?

```
[manager]
prepend_keymap = [
    { on   = [ "<Right>" ], run = "plugin fuse-archive --args=mount", desc = "Enter or Mount selected archive" },
    { on   = [ "<Left>" ], run = "plugin fuse-archive --args=unmount", desc = "Leave or Unmount selected archive" },
]
```

With that configuration, you can try the steps I included in my previous post.

**Comment by og900aero** [comment]
> If you have to mount the archive manually, you are probably not using `fuse-archive`, you are probably using some yazi feature, and that is why it is not unmounting later on.
> 
> If you want to use the plugin as described in the README, you need to configure some key bindings so things happen automatically:
> 
> [Usage](https://github.com/dawsers/fuse-archive.yazi#usage)
> 
> Have you done this?
> 
> ```
> [manager]
> prepend_keymap = [
>     { on   = [ "<Right>" ], run = "plugin fuse-archive --args=mount", desc = "Enter or Mount selected archive" },
>     { on   = [ "<Left>" ], run = "plugin fuse-archive --args=unmount", desc = "Leave or Unmount selected archive" },
> ]
> ```
> 
> With that configuration, you can try the steps I included in my previous post.

Ohh. I use different plugin for Right key:

{ on = [ "<Right>" ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

Because I use Right for enter directory or open file.
But never mind, because I like the manual mount and unmount function too.

**Comment by dawsers** [comment]
`fuse-archive` also implements smart enter. You need to add this to your `init.lua`, as explained in [options](https://github.com/dawsers/fuse-archive.yazi#options):

```
require("fuse-archive"):setup({
  smart_enter = true,
})
```

then, add this to `keymaps.toml`:

```
[manager]
prepend_keymap = [
    { on   = [ "<Right>" ], run = "plugin fuse-archive --args=mount", desc = "Enter or Mount selected archive" },
    { on   = [ "<Left>" ], run = "plugin fuse-archive --args=unmount", desc = "Leave or Unmount selected archive" },
]
```

You will have both smart enter and automounting of archives.

**Comment by og900aero** [comment]
Whoaaa, it is working fine! Thanx!
